Repository owncloud/files_antivirus, pull requests merged in 2018-11, with the labels that each got.

#266 failOnWarning="true"
  tests/unit/phpunit.xml
Labels: 3 - To review

#268 Add more tests on drone, remove surutinizer
  .drone.yml
  .scrutinizer.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#269 remove .travis.yml file as all tests are now in drone
  .travis.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#270 Adjust acceptance test steps changed in core
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review, QA, dev:acceptance-tests

#271 Adjust user creation test steps
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#276 check upload when using async move
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests

#277 Set version to 0.14.0, update changelog
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review
