Repository owncloud/files_antivirus, pull requests merged in 2018-08, with the labels that each got.

#248 Use ocPath via testing app
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
  tests/acceptance/features/bootstrap/AntivirusContext.php
  tests/acceptance/run.sh
Labels: 3 - To review

#250 Acceptance test code standard
  tests/acceptance/features/bootstrap/AntivirusContext.php
Labels: 2 - Developing, dev:acceptance-tests

#253 fixup modifyAppConfigs method name
  tests/acceptance/features/bootstrap/AntivirusContext.php
Labels: 3 - To review, QA-team, dev:acceptance-tests

#256 add PHP 7.2 for unit tests
  .drone.yml
Labels: 3 - To review, QA-team

#257 Use server for acceptance tests
  .drone.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#254 su-exec www-data is not needed for acceptance tests
  .drone.yml
Labels: 3 - To review, QA-team, dev:acceptance-tests

#258 Correct the expected old chunking status
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review, QA-team, dev:acceptance-tests
