Repository owncloud/files_antivirus, pull requests merged in 2018-12, with the labels that each got.

#279 Release 0.14.0
  CHANGELOG.md
  Makefile
  appinfo/info.xml
Labels: 3 - To review

#273 Move phpunit.xml to root folder of repo
  .drone.yml
  .gitignore
  Makefile
  composer.json
  composer.lock
  phpunit.xml
  templates/settings.php
  tests/unit/phpunit.xml
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To review, QA-team

#281 Adjust build status for drone
  README.md
Labels: 4 - To release, QA-team

#283 Remove leftover lint in Makefile
  Makefile
Labels: 4 - To release, QA-team

#284 use bootstrap.php of core acceptance tests
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#260 Add a diagnosis message to bgjob
  lib/BackgroundScanner.php
Labels: 3 - To review
