Repository owncloud/files_antivirus, pull requests merged in 2018-07, with the labels that each got.

#238 Release/0.13.0
  CHANGELOG.md
  appinfo/info.xml
  lib/Item.php
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review, QA, QA-ready

#242 use real clamAV for acceptance tests
  .drone.yml
  tests/acceptance/data/eicar.com
  tests/acceptance/data/eicar_com.zip
  tests/acceptance/data/eicarcom2.zip
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review, enhancement

#243 add create-bucket command
  .drone.yml
Labels: 3 - To review

#245 test to check the file size setting
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/bootstrap/AntivirusContext.php
Labels: 3 - To review

#246 test different dav api versions
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review

#247 Fixup refactored core gherkin steps
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
Labels: 3 - To review
