Repository owncloud/files_antivirus, pull requests merged in 2019-12, with the labels that each got.

#338 Adjust tests
  .drone.starlark
  .drone.yml
  composer.json
  composer.lock
  phpunit.xml
  tests/unit/ActivityTest.php
  tests/unit/AvirWrapperTest.php
  tests/unit/ChunkUploadTest.php
  tests/unit/Controller/SettingsControllerTest.php
  tests/unit/Cron/TaskTest.php
  tests/unit/ItemTest.php
  tests/unit/RequestHelperTest.php
  tests/unit/Scanner/LocalTest.php
  tests/unit/StatusTest.php
  tests/unit/TestBase.php
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team

#339 Add sabre/xml to behat dependencies
  .drone.starlark
  .drone.yml
  vendor-bin/behat/composer.json
Labels: 3 - To review, QA-team, dev:acceptance-tests

#342 Fix: timing issue of clamav
  .drone.starlark
  .drone.yml
Labels: 3 - To review, QA-team

#343 Coding standard 2.0.0
  .drone.starlark
  .drone.yml
  tests/unit/AvirWrapperTest.php
  tests/unit/Scanner/DaemonTest.php
  tests/unit/Scanner/LocalTest.php
  tests/unit/Scanner/SocketTest.php
  vendor-bin/owncloud-codestyle/composer.json
Labels: 3 - To review, QA-team

#344 wait for clamav in all configure-app steps
  .drone.starlark
  .drone.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#347 Change docker image which waits for virus db update, increase wait
  .drone.starlark
  .drone.yml
Labels: 3 - To review, Drone, QA-team
