Repository owncloud/files_antivirus, pull requests merged in 2020-07, with the labels that each got.

#371 [Tests-Only] Adjust wait for clamav docker to pull
  .drone.star
Labels: 3 - To review, QA-team

#373 Objectstore implementations do no use part files - as a result Permis…
  lib/AvirWrapper.php
Labels: 3 - To review, bug

#376 Add tests and make unlink return bool according to its PHPDoc
  lib/AvirWrapper.php
  tests/unit/AvirWrapperTest.php
Labels: 3 - To review
