Repository owncloud/files_antivirus, pull requests merged in 2021-04, with the labels that each got.

#416 Wait for icap service before running unit tests
  .drone.star
Labels: QA:team

#418 [tests-only] Activity app now requires core 10.7.1
  .drone.star
Labels: QA:team

#399 Prefer daemon or socket to executable mode to if any of those is available
  appinfo/install.php
  lib/AppConfig.php
  lib/AppInfo/Application.php
Labels: 3 - To review, enhancement

#423 Improve validation pattern to check whether port number is in [1, 65535] range
  templates/settings.php
Labels: 3 - To review

#428 Do not depend on the sockets PHP extension
  lib/Scanner/ICAPClient.php
Labels: 3 - To review
