Repository owncloud/files_antivirus, pull requests merged in 2021-03, with the labels that each got.

#403 [tests-only] Specify skeleton in tests
  tests/acceptance/features/apiAntivirus/antivirusFileSize.feature
  tests/acceptance/features/apiAntivirus/antivirusMain.feature
  tests/acceptance/features/webUIActivityList/activityList.feature
Labels: 3 - To review, QA-team

#398 Get rid of update.php and preupdate.php
  appinfo/Migrations/Version20210212155302.php
  appinfo/Migrations/Version20210212160142.php
  appinfo/preupdate.php
  appinfo/update.php
Labels: 3 - To review

#409 [tests-only] run tests on icap
  .drone.star
Labels: QA:team
